# -*- mode: python -*-
# GtkRadiant build scripts
# TTimo <ttimo@ttimo.net>
# http://scons.org/

import os

Import( [ 'utils', 'config', 'settings', 'project', 'shlib_objects' ] )

( libpath, libname ) = os.path.split( project )
libname = os.path.splitext( libname )[0]

env = Environment( ENV = os.environ )

useJPEG = True
useGtk = True
useZ = True
usePNG = True

settings.SetupEnvironment( env, config['name'], useGtk = useGtk, useJPEG = useJPEG, useZ = useZ, usePNG = usePNG )
proj = utils.vcxproj( os.path.join( GetLaunchDir(), project ) )

# some filtering. may need to improve that
add_sources = []
( drop, files ) = proj.filterSource( r'.*l_net_wins\.c' )
if ( len( drop ) != 0 ):
	add_sources.append( 'l_net_berkeley.c' )

module_base = env.SharedLibrary( os.path.join( 'modules', libname ), shlib_objects + [ os.path.join( libpath, i ) for i in files ] )
module = env.AddPostAction( module_base, utils.CheckUnresolved )

Return( 'module' )
