#!/bin/bash

RADIANT_HOME=$(dirname "$0")
RADIANT_HOME=${RADIANT_HOME/GtkRadiant.app*/GtkRadiant.app}

echo
echo "Starting GtkRadiant in ${RADIANT_HOME}"
echo

set -x

GTK_RUNTIME="${RADIANT_HOME}/Contents/Resources/gtk-runtime"

export GDK_PIXBUF_MODULE_FILE="${GTK_RUNTIME}/etc/gtk-2.0/gdk-pixbuf.loaders"

export GTK_DATA_PREFIX="${GTK_RUNTIME}"
export GTK_EXE_PREFIX="${GTK_RUNTIME}"
export GTK_PATH="${GTK_RUNTIME}"

export PANGO_SYSCONFDIR="${GTK_RUNTIME}/etc"
export PANGO_LIBDIR="${GTK_RUNTIME}/lib"

"${RADIANT_HOME}/Contents/MacOS/radiant.bin"