#!/bin/bash

RADIANT_HOME=$(dirname "$0")
RADIANT_HOME=${RADIANT_HOME/GtkRadiant.app*/GtkRadiant.app}

echo
echo "Starting GtkRadiant in ${RADIANT_HOME}"
echo

set -x

resources="${RADIANT_HOME}/Contents/Resources"

export GDK_PIXBUF_MODULE_FILE="${resources}/etc/gtk-2.0/gdk-pixbuf.loaders"

export GTK_DATA_PREFIX="${resources}"
export GTK_EXE_PREFIX="${resources}"
export GTK_PATH="${resources}"

export PANGO_SYSCONFDIR="${resources}/etc"
export PANGO_LIBDIR="${resources}/lib"

cd "${resources}/install"
./radiant.bin $@

set +x