#!/bin/sh

# what I use to run this script on my win32 box:
# have cygwin, perl (ActiveState) and the cygwin zip utility
# for zip: http://www.hirmke.de/software/develop/gnuwin32/cygwin/porters/Hirmke_Michael/GNUWin32-links.html#zip-2.3%20(cygwin1.1)

# FIXME: I'd like to have this same script used for both platforms
# for the SDK we recreate a smaller tree and only put the stuff we want
# what potentially changes across platforms is the binaries and the src/ subtree for gtk stuff

# proceed in order:

# include directory for all plugin API
mkdir GtkRadiant
mkdir GtkRadiant/include
rm -rf ./GtkRadiant/include/*
echo "Copying GtkRadiant API headers"
cp ../../include/* ./GtkRadiant/include

# now fill in the plugins menu:
# copy common, textool and the sample plugin
mkdir GtkRadiant
mkdir GtkRadiant/plugins
mkdir GtkRadiant/plugins/common
mkdir GtkRadiant/plugins/textool
mkdir GtkRadiant/plugins/sample
rm -rf ./GtkRadiant/plugins/*
echo "Copying TexTool"
cp -R ../../plugins/textool ./GtkRadiant/plugins/textool
cp -R ../../plugins/common ./GtkRadiant/plugins/common
echo "Copying Sample plugin"
cp -R ../../plugins/sample ./GtkRadiant/plugins/sample

# get gtkradiant binary (you know you want it)
# FIXME: for win32 SDK only
#cp ../radiant/Release/Q3Radiant.exe GtkRadiant.exe

# grab the gtk devel package
# FIXME: for win32 SDK only
echo "Updating src/"
echo "NOTE: check we are using the latest gtk dev packages"
echo "NOTE: we are not putting our patched versions in"
rm -rf src
unzip /cygdrive/c/Download/Gtk-20001023/glib-dev-20001023.zip
unzip /cygdrive/c/Download/Gtk-20001023/gtk+-dev-20000722.zip
unzip /cygdrive/c/Download/Gtk-20001023/libiconv-dev-20001007.zip
unzip /cygdrive/c/Download/Gtk-20001023/extralibs-dev-20001007.zip
# grab the src/build directory, we use it with the cygwin makefiles
cp -R ../../../src/build src

# build the SDK
#echo "Check the sample/ directory is clean"
#zip -r PluginSDK.zip src private sample README.html GtkRadiant.exe